name: Build and Deploy FlowKit Docs

on:
  push:
    branches:
      - docs

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-copybutton sphinx_design sphinx_external_toc ansys-sphinx-theme myst-parser

      - name: Clean previous build
        run: rm -rf doc/_build/html

      - name: Build documentation
        run: sphinx-build -b html doc/source doc/_build/html

      - name: Confirm built content
        run: |
          echo "::group::Built Files"
          ls -la doc/_build/html
          echo "::endgroup::"
          echo "::group::index.html Preview"
          head -n 30 doc/_build/html/index.html || true
          echo "::endgroup::"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: doc/_build/html
          force_orphan: true
